name: Get xgameruntime and build.
on: workflow_dispatch

jobs:
    xgameruntime:
        runs-on: windows-latest
        steps:
            - name: Install GDK
              shell: pwsh
              continue-on-error: true
              run: |
                  winget install Microsoft.Gaming.GDK --silent --accept-package-agreements --accept-source-agreements

            - name: Find xgameruntime.
              shell: pwsh
              run: |
                  New-Item -ItemType Directory -Path out | Out-Null
                  Get-ChildItem "C:\Program Files\WindowsApps" -Recurse -Filter 'xgameruntime*' -File |
                    ForEach-Object {
                      Write-Host $_.FullName
                      Copy-Item $_.FullName -Destination ("out\" + "xgameruntime.dll.threading")
                    }

            - uses: actions/upload-artifact@v4
              with:
                  name: xgameruntime
                  path: out/
    build:
        runs-on: ubuntu-latest
        needs: xgameruntime
        steps:
            - uses: actions/checkout@v4

            - name: Download xgameruntime
              uses: actions/download-artifact@v4
              with:
                  name: xgameruntime

            - name: Move xgameruntime to build directory
              run: |
                  ls
                  mkdir -p build/extra
                  mv xgameruntime/xgameruntime.dll.threading build/extra/xgameruntime.dll.threading
                  cd build/extra
                  ls
                  cd ../..

            - name: Run build script
              run: |
                  ./build.sh
