name: Download xgameruntime, build WineGDK, and release patched Proton.
on:
    push:
        tags:
            - "*"

jobs:
    xgameruntime:
        runs-on: windows-latest
        steps:
            - name: Install GDK
              shell: pwsh
              continue-on-error: true
              run: |
                  winget install Microsoft.Gaming.GDK --silent --accept-package-agreements --accept-source-agreements

            - name: Find xgameruntime.
              shell: pwsh
              run: |
                  New-Item -ItemType Directory -Path out | Out-Null
                  Get-ChildItem "C:\Program Files\WindowsApps" -Recurse -Filter 'xgameruntime*' -File |
                    ForEach-Object {
                      Write-Host $_.FullName
                      Copy-Item $_.FullName -Destination ("out\" + "xgameruntime.dll.threading")
                    }

            - uses: actions/upload-artifact@v4
              with:
                  name: xgameruntime
                  path: out/
    build:
        runs-on: ubuntu-latest
        needs: xgameruntime
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Wine build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends \
                    build-essential flex bison pkg-config \
                    gcc-multilib gcc-mingw-w64 \
                    libasound2-dev bluez libpulse-dev libdbus-1-dev \
                    libfontconfig-dev libfreetype-dev libgnutls28-dev \
                    libgl-dev libunwind-dev libx11-dev libxcomposite-dev \
                    libxcursor-dev libxfixes-dev libxi-dev libxrandr-dev \
                    libxrender-dev libxext-dev \
                    libwayland-bin libwayland-dev libegl-dev \
                    libxkbcommon-dev libxkbregistry-dev \
                    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
                    libsdl2-dev libudev-dev libvulkan-dev \
                    libcapi20-dev libcups2-dev libgphoto2-dev libsane-dev \
                    libkrb5-dev samba-dev ocl-icd-opencl-dev libpcap-dev \
                    libusb-1.0-0-dev libv4l-dev

            - name: Download xgameruntime
              uses: actions/download-artifact@v4
              with:
                  name: xgameruntime

            - name: Move xgameruntime to build directory
              run: |
                  mkdir -p build/extra
                  mv xgameruntime.dll.threading build/extra/xgameruntime.dll.threading

            - name: Run build script
              run: |
                  ./build.sh

            - name: Upload release artifacts
              uses: actions/upload-artifact@v4
              with:
                  path: GDK-Proton*.tar.gz

            - uses: softprops/action-gh-release@v1
              with:
                  files: GDK-Proton*.tar.gz
